version: '3'
services:
  rails:
    build:
      context: ./src/api
    env_file:
      - ./environments/db.env
      - ./environments/credentials.env
    command: bundle exec puma -C config/puma.rb
    volumes:
      - ./src/api:/webapp
      - public-data:/webapp/public
      - tmp-data:/webapp/tmp
      - log-data:/webapp/log
      - ./logs/web/rails:/webapp/log
    depends_on:
      - db

  db:
#    build:
#      context: provision/db
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql

  api:
    build:
      context: provision/nginx
    volumes:
      - public-data:/webapp/public
      - tmp-data:/webapp/tmp
    ports:
      - 9000:80
      -
    depends_on:
      - rails

  proxy:
    build:
      context: provision/proxy
    volumes:
      - ./logs/web/proxy:/var/log/proxy
    ports:
      - 80:80
    depends_on:
      - front
      - services
      - admin

  front:
    build:
      context: provision/front
    volumes:
      - ./src/front:/front

  careers:
    build:
      context: provision/careers
    volumes:
      - ./src/careers:/webapp

  services:
    build:
      context: provision/services
    volumes:
      - ./src/services:/webapp

  admin:
    build:
      context: provision/admin
    volumes:
      - ./src/admin/public:/webapp

  yarn_front:
    build:
      context: provision/yarn_front
    volumes:
      - ./src/front:/front
    command: yarn install

  yarn_careers:
    build:
      context: provision/yarn_careers
    volumes:
      - ./src/careers:/careers
    command: yarn install

  yarn_services:
    build:
      context: provision/yarn_services
    volumes:
      - ./src/services:/services
    command: yarn install

  yarn_admin:
    build:
      context: provision/yarn_admin
    volumes:
      - ./src/admin:/admin
    command: yarn install

volumes:
  public-data:
  tmp-data:
  log-data:
  db-data:
  bundle-data: