- name: install docker
  shell: wget -qO- https://get.docker.com/ | sh

- name: add group to docker
  shell: usermod -aG docker vagrant

- name: start and enable docker
  service: name=docker state=started enabled=yes

- name: install epel
  yum: name=epel-release state=present

- name: install python-pip
  yum: name=python-pip state=present

- name: pip install docker-compose
  pip: name=docker-compose
