default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch('MYSQL_USER') { 'arms_admin' } %>
  password: <%= ENV.fetch('MYSQL_PASSWORD') { 'pass' } %>
  host: db

development:
  <<: *default
  database: arms_web_dev

test:
  <<: *default
  database: arms_web_test